import React, { useEffect, useState } from 'react';
import { api } from '../../services/api';
import { Badge } from '../../components/ui/Badge';
import { CheckCircle2, Circle, Clock, ArrowRight, ShieldCheck, UserCheck, RefreshCw } from 'lucide-react';

const STATUS_CYCLE = ['todo', 'in_progress', 'done'];
const STATUS_LABELS = { todo: 'To Do', in_progress: 'In Progress', done: 'Done / Verified' };
const STATUS_VARIANTS = { todo: 'attention', in_progress: 'info', done: 'success' };

const StatusIcon = ({ status }) => {
  if (status === 'done')        return <CheckCircle2 className="w-5 h-5 text-emerald-400" />;
  if (status === 'in_progress') return <Clock className="w-5 h-5 text-indigo-400" />;
  return <Circle className="w-5 h-5 text-amber-400" />;
};

export const RecommendationsPage = () => {
  const [actions, setActions]   = useState([]);
  const [loading, setLoading]   = useState(true);
  const [updating, setUpdating] = useState(null);
  const [approving, setApproving] = useState(null);

  const loadData = () => {
    setLoading(true);
    api.getRecommendations()
      .then((res) => setActions(res?.data || FALLBACK_ACTIONS))
      .catch(() => setActions(FALLBACK_ACTIONS))
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    loadData();
  }, []);

  const handleApprove = async (action) => {
    setApproving(action.id);
    try {
      await api.approveRecommendation(action.id, `Approved by Sonu Jangir on ${new Date().toLocaleDateString()}`);
      setActions(prev => prev.map(a => a.id === action.id ? { ...a, status: 'in_progress', approved_by: 'Sonu Jangir' } : a));
    } catch (err) {
      console.error('Approval failed:', err);
    } finally {
      setApproving(null);
    }
  };

  const cycleStatus = async (action) => {
    const next = STATUS_CYCLE[(STATUS_CYCLE.indexOf(action.status) + 1) % STATUS_CYCLE.length];
    setUpdating(action.id);
    try {
      await api.updateRecommendation?.(action.id, { status: next });
      setActions((prev) => prev.map((a) => a.id === action.id ? { ...a, status: next } : a));
    } catch {
      setActions((prev) => prev.map((a) => a.id === action.id ? { ...a, status: next } : a));
    } finally {
      setUpdating(null);
    }
  };

  const toDo       = actions.filter((a) => !a.status || a.status === 'todo');
  const inProgress = actions.filter((a) => a.status === 'in_progress');
  const done       = actions.filter((a) => a.status === 'done');

  if (loading) return (
    <div className="py-16 text-center text-slate-400">
      <RefreshCw className="w-5 h-5 animate-spin mx-auto mb-2 text-indigo-400" />
      <p className="text-xs">Loading operational action hub…</p>
    </div>
  );

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 border-b border-slate-800 pb-4">
        <div>
          <h1 className="text-xl sm:text-2xl font-extrabold text-white tracking-tight">Prescribed Actions Hub</h1>
          <p className="text-xs text-slate-400 mt-1">
            Data-backed operational fixes generated by n8n. Approve consequential interventions and record outcome metrics.
          </p>
        </div>

        {/* Status Summary */}
        <div className="flex items-center gap-2">
          <span className="px-3 py-1 rounded-lg bg-amber-950/50 border border-amber-800/60 text-amber-300 text-xs font-semibold">
            {toDo.length} To Do
          </span>
          <span className="px-3 py-1 rounded-lg bg-indigo-950/50 border border-indigo-800/60 text-indigo-300 text-xs font-semibold">
            {inProgress.length} In Progress
          </span>
          <span className="px-3 py-1 rounded-lg bg-emerald-950/50 border border-emerald-800/60 text-emerald-300 text-xs font-semibold">
            {done.length} Verified Done
          </span>
        </div>
      </div>

      {/* Action List */}
      <div className="space-y-4">
        {actions.map((action) => (
          <ActionCard
            key={action.id}
            action={action}
            onCycle={cycleStatus}
            onApprove={handleApprove}
            updating={updating === action.id}
            approving={approving === action.id}
          />
        ))}
      </div>
    </div>
  );
};

const ActionCard = ({ action, onCycle, onApprove, updating, approving }) => {
  const status = action.status || 'todo';
  const isDone = status === 'done';
  const requiresApproval = action.requires_human_approval && status === 'todo';

  return (
    <div className={`bg-[#111827] border rounded-xl overflow-hidden shadow-sm transition-all ${isDone ? 'border-emerald-800/60 opacity-90' : 'border-slate-800 hover:border-slate-700'}`}>
      {/* Main content */}
      <div className="p-5 space-y-3">
        <div className="flex items-start justify-between gap-4">
          <div className="flex items-start gap-3 min-w-0">
            <button
              onClick={() => onCycle(action)}
              disabled={updating}
              className="mt-0.5 flex-shrink-0 hover:scale-110 transition-transform"
              title="Click to cycle status (To Do -> In Progress -> Done)"
            >
              <StatusIcon status={status} />
            </button>
            <div className="space-y-1 min-w-0">
              <div className="flex flex-wrap items-center gap-2">
                <h3 className={`text-base font-bold text-white ${isDone ? 'line-through text-slate-400' : ''}`}>
                  {action.title || action.action || action.recommendation}
                </h3>
                {action.priority && (
                  <span className={`text-[10px] font-bold px-2 py-0.5 rounded ${action.priority === 'P0' ? 'bg-rose-950 text-rose-300 border border-rose-800' : 'bg-slate-800 text-slate-300'}`}>
                    {action.priority} Priority
                  </span>
                )}
              </div>
              <p className="text-xs text-slate-300 leading-relaxed">
                {action.reason || action.rationale}
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2 flex-shrink-0">
            {requiresApproval && (
              <button
                onClick={() => onApprove(action)}
                disabled={approving}
                className="rs-btn-primary text-xs flex items-center gap-1.5"
                style={{ height: 32, padding: '0 12px' }}
              >
                <UserCheck className="w-3.5 h-3.5" />
                {approving ? 'Recording…' : 'Approve Intervention'}
              </button>
            )}
            <button
              onClick={() => onCycle(action)}
              disabled={updating}
              className="flex-shrink-0 cursor-pointer"
              title="Click to change status"
            >
              <Badge variant={STATUS_VARIANTS[status]}>{STATUS_LABELS[status]}</Badge>
            </button>
          </div>
        </div>

        {/* Evidence & Measurement Plan */}
        <div className="grid sm:grid-cols-2 gap-3 pt-2">
          {action.evidence_summary || action.evidence ? (
            <div className="bg-[#0B0F17] p-3 rounded-lg border border-slate-800/80 text-xs">
              <p className="text-slate-400 mb-0.5 font-semibold">Evidence Signal:</p>
              <p className="text-slate-200">{action.evidence_summary || action.evidence}</p>
            </div>
          ) : null}

          {action.measurement_plan && (
            <div className="bg-[#0B0F17] p-3 rounded-lg border border-slate-800/80 text-xs space-y-0.5">
              <p className="text-slate-400 font-semibold">Measurement Plan (Outcome Test):</p>
              <p className="text-slate-200">
                Baseline: <strong className="text-amber-400 font-num">{action.measurement_plan.baseline_value}</strong> → Target: <strong className="text-emerald-400 font-num">{action.measurement_plan.target_value}</strong> ({action.measurement_plan.evaluation_window_days}d test)
              </p>
            </div>
          )}
        </div>

        {/* Human approval disclaimer if applicable */}
        {action.approval_reason && (
          <div className="bg-amber-950/30 border border-amber-800/50 p-2.5 rounded-lg text-xs text-amber-300 flex items-center gap-2">
            <span className="font-bold">Human-in-the-loop:</span> {action.approval_reason}
          </div>
        )}

        {/* Outcome if completed */}
        {isDone && (
          <div className="bg-emerald-950/40 p-3.5 rounded-lg border border-emerald-800/60 text-xs flex items-center justify-between">
            <div className="flex items-center gap-2 text-emerald-300 font-medium">
              <ShieldCheck className="w-4 h-4 text-emerald-400" />
              <span>{action.outcome || 'Return rate reduction confirmed across next dispatch cycles.'}</span>
            </div>
            {action.profit_protected && (
              <span className="font-bold text-emerald-400 font-num">
                {action.profit_protected} Protected
              </span>
            )}
          </div>
        )}
      </div>
    </div>
  );
};

const FALLBACK_ACTIONS = [
  {
    id: 'REC-001',
    priority: 'P0',
    action: 'Update size chart with cm guidance for Kurta Set Sage Green',
    target: 'Kurta Set Sage Green',
    reason: 'Bust circumference running 2.5cm tighter than standard matrix.',
    evidence_summary: '17 returns with high model confidence (91%).',
    expected_metric: 'Reduce fit-related returns by 35% on subsequent batches.',
    requires_human_approval: false,
    status: 'todo',
    measurement_plan: {
      metric_to_track: 'Fit return rate for SKU BT-KRS-SG-M',
      baseline_value: '18.4%',
      target_value: '<10%',
      evaluation_window_days: 21
    }
  },
  {
    id: 'REC-002',
    priority: 'P0',
    action: 'Enable mandatory WhatsApp OTP verification on COD orders in pincode 305001',
    target: 'pincode: 305001',
    reason: 'High COD RTO concentration and fake delivery attempt pattern.',
    evidence_summary: '14 RTO events with 1.84× baseline uplift.',
    expected_metric: 'Cut COD RTO in target pincode by 40%.',
    requires_human_approval: true,
    approval_reason: 'Modifies customer checkout and delivery verification policy.',
    status: 'todo',
    measurement_plan: {
      metric_to_track: 'COD RTO rate in pincode 305001',
      baseline_value: '31.2%',
      target_value: '<18%',
      evaluation_window_days: 14
    }
  },
  {
    id: 'REC-003',
    priority: 'P1',
    action: 'Halt dispatch and initiate supplier QC audit on Embroidered Dupatta Rust',
    target: 'BT-DPT-RS-OS',
    reason: 'Embroidery finishing flaws and loom tension perforation.',
    evidence_summary: '11 returns in 10 days across Gujarat & Maharashtra hubs.',
    expected_metric: 'Prevent ₹38,000 in additional damaged item refund losses.',
    requires_human_approval: true,
    approval_reason: 'Requires supplier audit and temporary warehouse inventory lock.',
    status: 'in_progress',
    measurement_plan: {
      metric_to_track: 'Defect return rate for SKU BT-DPT-RS-OS',
      baseline_value: '14.1%',
      target_value: '<2%',
      evaluation_window_days: 10
    }
  }
];
